CREATE TABLE app_user (
 id BIGSERIAL PRIMARY KEY,
 username VARCHAR(100) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 role VARCHAR(30) NOT NULL,
 enabled BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customer (
 id BIGSERIAL PRIMARY KEY,
 name VARCHAR(150) NOT NULL,
 email VARCHAR(255),
 phone VARCHAR(30),
 address VARCHAR(500),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product (
 id BIGSERIAL PRIMARY KEY,
 name VARCHAR(150) NOT NULL,
 sku VARCHAR(80) NOT NULL UNIQUE,
 price NUMERIC(14,2) NOT NULL,
 stock_quantity INTEGER NOT NULL DEFAULT 0,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customer_order (
 id BIGSERIAL PRIMARY KEY,
 customer_id BIGINT NOT NULL REFERENCES customer(id),
 status VARCHAR(30) NOT NULL,
 total_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_item (
 id BIGSERIAL PRIMARY KEY,
 order_id BIGINT NOT NULL REFERENCES customer_order(id) ON DELETE CASCADE,
 product_id BIGINT NOT NULL REFERENCES product(id),
 quantity INTEGER NOT NULL,
 unit_price NUMERIC(14,2) NOT NULL
);
