import React,{useEffect,useState} from 'react'; import {createRoot} from 'react-dom/client'; import axios from 'axios'; import './style.css';
const api=axios.create({baseURL:'http://localhost:8080/api'}); api.interceptors.request.use(c=>{const t=localStorage.getItem('token');if(t)c.headers.Authorization=`Bearer ${t}`;return c});
function Login({onLogin}:{onLogin:()=>void}){const [u,setU]=useState('admin'),[p,setP]=useState('Admin@123'),[err,setErr]=useState('');
const submit=async(e:any)=>{e.preventDefault();try{const r=await api.post('/auth/login',{username:u,password:p});localStorage.setItem('token',r.data.token);onLogin()}catch{setErr('Invalid username or password')}};return <div className="login"><form onSubmit={submit}><h1>Business Platform</h1><input value={u} onChange={e=>setU(e.target.value)} placeholder="Username"/><input value={p} onChange={e=>setP(e.target.value)} type="password" placeholder="Password"/><button>Login</button>{err&&<p>{err}</p>}</form></div>}
function App(){const [tab,setTab]=useState('dashboard'),[customers,setCustomers]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[orders,setOrders]=useState<any[]>([]);
const load=async()=>{const [c,p,o]=await Promise.all([api.get('/customers'),api.get('/products'),api.get('/orders')]);setCustomers(c.data);setProducts(p.data);setOrders(o.data)};useEffect(()=>{load()},[]);
return <div className="app"><aside><h2>Business</h2>{['dashboard','customers','products','orders'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}<button onClick={()=>{localStorage.removeItem('token');location.reload()}}>Logout</button></aside><main><h1>{tab[0].toUpperCase()+tab.slice(1)}</h1>{tab==='dashboard'?<div className="cards"><div>Customers<strong>{customers.length}</strong></div><div>Products<strong>{products.length}</strong></div><div>Orders<strong>{orders.length}</strong></div></div>:<Table data={tab==='customers'?customers:tab==='products'?products:orders}/>}</main></div>}
function Table({data}:{data:any[]}){return <table><thead><tr>{data[0]&&Object.keys(data[0]).slice(0,6).map(k=><th>{k}</th>)}</tr></thead><tbody>{data.map((r,i)=><tr key={i}>{Object.keys(r).slice(0,6).map(k=><td>{String(r[k]??'')}</td>)}</tr>)}</tbody></table>}
function Root(){const [auth,setAuth]=useState(!!localStorage.getItem('token'));return auth?<App/>:<Login onLogin={()=>setAuth(true)}/>};createRoot(document.getElementById('root')!).render(<Root/>);
